install:
  # Latest version of Node
  - ps: Install-Product node ''
  - npm config set spin false
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test

matrix:
  fast_finish: true

build: off